### ISSUE TITLE
ROS2 foxy run error

### ISSUE THREAD

**Issue by blaoke** [ros-visualization/rqt_bag#135]
My ros2 is foxy, but  I can't find foxy-devel in this repository branch. when I clone humble branch and colcon build, It's successful. 
But when I run rqt_bag,  got an error like follow:

```
RosPluginProvider.load(rqt_bag/Bag) exception raised in __builtin__.__import__(rqt_bag.bag, [Bag]):
Traceback (most recent call last):
  File "/home/lb/ros2_foxy/install/rqt_gui/lib/python3.8/site-packages/rqt_gui/ros_plugin_provider.py", line 80, in load
    module = __builtin__.__import__(
  File "/home/lb/ros2_foxy/install/rqt_bag/lib/python3.8/site-packages/rqt_bag/__init__.py", line 34, in <module>
    from rqt_bag.plugins.message_view import MessageView
  File "/home/lb/ros2_foxy/install/rqt_bag/lib/python3.8/site-packages/rqt_bag/plugins/message_view.py", line 36, in <module>
    import rosbag2_py
ModuleNotFoundError: No module named 'rosbag2_py'

PluginManager._load_plugin() could not load plugin "rqt_bag/Bag":
Traceback (most recent call last):
  File "/home/lb/ros2_foxy/install/qt_gui/lib/python3.8/site-packages/qt_gui/plugin_handler.py", line 102, in load
    self._load()
  File "/home/lb/ros2_foxy/install/qt_gui/lib/python3.8/site-packages/qt_gui/plugin_handler_direct.py", line 55, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/home/lb/ros2_foxy/install/qt_gui/lib/python3.8/site-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/home/lb/ros2_foxy/install/qt_gui/lib/python3.8/site-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/home/lb/ros2_foxy/install/rqt_gui_py/lib/python3.8/site-packages/rqt_gui_py/ros_py_plugin_provider.py", line 69, in load
    return super(RosPyPluginProvider, self).load(plugin_id, ros_plugin_context)
  File "/home/lb/ros2_foxy/install/qt_gui/lib/python3.8/site-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/home/lb/ros2_foxy/install/rqt_gui/lib/python3.8/site-packages/rqt_gui/ros_plugin_provider.py", line 91, in load
    raise e
  File "/home/lb/ros2_foxy/install/rqt_gui/lib/python3.8/site-packages/rqt_gui/ros_plugin_provider.py", line 80, in load
    module = __builtin__.__import__(
  File "/home/lb/ros2_foxy/install/rqt_bag/lib/python3.8/site-packages/rqt_bag/__init__.py", line 34, in <module>
    from rqt_bag.plugins.message_view import MessageView
  File "/home/lb/ros2_foxy/install/rqt_bag/lib/python3.8/site-packages/rqt_bag/plugins/message_view.py", line 36, in <module>
    import rosbag2_py
ModuleNotFoundError: No module named 'rosbag2_py'
```

which branch can match ros2-foxy, or how can I solve this problem. Thanks !

**Comment by clalancette** [comment]
We never released this package for Foxy, so I don't think it works there.  The first time we released it was for Galactic, which uses the `ros2` branch.
