### ISSUE TITLE
cannot import name qInfo

### ISSUE THREAD

**Issue by fredbje** [ros-visualization/rqt_bag#20]
Hello, when I try to run rqt_bag from the terminal I get the following error:

```
Traceback (most recent call last):
  File "/opt/ros/kinetic/bin/rqt_bag", line 5, in <module>
    from rqt_bag.bag import Bag
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_bag/bag.py", line 39, in <module>
    from .bag_widget import BagWidget
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_bag/bag_widget.py", line 40, in <module>
    from python_qt_binding.QtCore import Qt, qInfo, qWarning, Signal
ImportError: cannot import name qInfo
```

**Comment by dirk-thomas** [comment]
Duplicate of #15.
