### ISSUE TITLE
Cannot launch with Ubuntu 16.04

### ISSUE THREAD

**Issue by VictorLamoine** [ros-visualization/rqt_bag#21]
Since a week or so, I cannot start rqt_bag:

```
$ rqt_bag
Traceback (most recent call last):
  File "/opt/ros/kinetic/bin/rqt_bag", line 5, in <module>
    from rqt_bag.bag import Bag
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_bag/bag.py", line 39, in <module>
    from .bag_widget import BagWidget
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_bag/bag_widget.py", line 40, in <module>
    from python_qt_binding.QtCore import Qt, qInfo, qWarning, Signal
ImportError: cannot import name qInfo
```

Also reported here:
https://answers.ros.org/question/274739/rqt_bag-cannot-import-name-qinfo/

This happened after a system update

**Comment by dirk-thomas** [comment]
Duplicate of #15.
