### ISSUE TITLE
rqt_bag crash when select all topic to record sometimes

### ISSUE THREAD

**Issue by lupeng880129** [ros-visualization/rqt_bag#34]
i used kinetic on Ubuntu16.04, and when i use rqt_bag to record all the topics it would crash and display the following error msg.
`Traceback (most recent call last):
  File "/home/lupeng/catkin_ws/src/rqt_bag/src/rqt_bag/timeline_frame.py", line 293, in paint
    self._draw_topic_dividers(painter)
  File "/home/lupeng/catkin_ws/src/rqt_bag/src/rqt_bag/timeline_frame.py", line 520, in _draw_topic_dividers
    (x, y, w, h) = self._history_bounds[topic]
KeyError: '/usb_cam/image_raw'
`

**Comment by ElonKou** [comment]
I have the same question.
what I do is add try catch for these codes.
https://github.com/ros-visualization/rqt_bag/blob/master/rqt_bag/src/rqt_bag/timeline_frame.py#L520-L530
It works ,but I don't know what happened.

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as May 31st 2025, so I'm closing this.

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
