### ISSUE TITLE
Next/prev buttons in raw view don't work in Noetic

### ISSUE THREAD

**Issue by JStech** [ros-visualization/rqt_bag#95]
In Noetic, after loading a bag and showing the raw display of a message, clicking the arrow buttons for next or previous message at the top of the message pane causes this error:
```
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_bag/plugins/topic_message_view.py", line 87, in navigate_previous
    for entry in self.timeline.get_entries([self.topic], self.timeline._timeline_frame.start_stamp, self.timeline._timeline_frame.playhead):
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_bag/bag_timeline.py", line 273, in get_entries
    for entry, _ in bag._mergesort(bag_entries, key=lambda entry: entry.time):
AttributeError: module 'rosbag.bag' has no attribute '_mergesort'
```

**Comment by JStech** [comment]
Got a similar error again, this time I think it was while the bag was being opened--no messages ever showed up, and then I saw this when I closed the window.
```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_bag/index_cache_thread.py", line 67, in run
    updated |= (self.timeline._update_index_cache(topic) > 0)
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_bag/timeline_frame.py", line 838, in _update_index_cache
    for entry in self.scene().get_entries(topic, start_time, end_time):
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_bag/bag_timeline.py", line 273, in get_entries
    for entry, _ in bag._mergesort(bag_entries, key=lambda entry: entry.time):
AttributeError: module 'rosbag.bag' has no attribute '_mergesort'
```

**Comment by JStech** [comment]
Sorry, I realized this is probably a duplicate of #90.
